# .github/workflows/python-publish.yml
name: Build and Publish Python Package

on:
  push:
    branches:
      - main  # Trigger the action on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the action on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build the distribution
        run: |
          python setup.py sdist bdist_wheel

      - name: Upload to GitHub Package Registry
        run: |
          python -m pip install twine
          TWINE_USERNAME=__token__ TWINE_PASSWORD=${{ secrets.GITHUB_TOKEN }} \
          python -m twine upload --repository-url https://upload.pypi.org/legacy/ dist/*